<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_Q-PTILQREeuju6Stncc5YQ" name="adaugareAnuntAgentDiagram" author="unciu" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_Q-PTIbQREeuju6Stncc5YQ" name="adaugareAnuntAgent">
      <elements xmi:type="process:Lane" xmi:id="_Q-PTIrQREeuju6Stncc5YQ" name="Agent" actor="_1_qQoLYwEeueft3gc972AA">
        <elements xmi:type="process:StartEvent" xmi:id="_Q-PTI7QREeuju6Stncc5YQ" name="Accesare platforma" outgoing="_Q-PTOLQREeuju6Stncc5YQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Q-PTJLQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Q-PTJbQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Q-PTJrQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Q-PTJ7QREeuju6Stncc5YQ" name="Introducere date anunt" outgoing="_h6jqULQREeuju6Stncc5YQ" incoming="_Q-PTOLQREeuju6Stncc5YQ _8lHBYLQREeuju6Stncc5YQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Q-PTKLQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Q-PTKbQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Q-PTKrQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_mzKmYLYyEeueft3gc972AA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mzKmYbYyEeueft3gc972AA" name="anunt" content="anunt" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAnuntAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mzKmYrYyEeueft3gc972AA" name="anunt" dataType="_Q-PTVLQREeuju6Stncc5YQ" className="com.luxmob.model.DMAnuntAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mzKmY7YyEeueft3gc972AA" name="anuntInput.descriereAnunt" content="anuntInput?.descriereAnunt" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mzKmZLYyEeueft3gc972AA" name="anuntInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mzKmZbYyEeueft3gc972AA" type="JAVA_METHOD" expression="setDescriereAnunt">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_mzKmZrYyEeueft3gc972AA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mzKmZ7YyEeueft3gc972AA" name="anunt" content="anunt" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAnuntAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mzKmaLYyEeueft3gc972AA" name="anunt" dataType="_Q-PTVLQREeuju6Stncc5YQ" className="com.luxmob.model.DMAnuntAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mzKmabYyEeueft3gc972AA" name="anuntInput.titluAnunt" content="anuntInput?.titluAnunt" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mzKmarYyEeueft3gc972AA" name="anuntInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mzKma7YyEeueft3gc972AA" type="JAVA_METHOD" expression="setTitluAnunt">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_mzKmbLYyEeueft3gc972AA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mzKmbbYyEeueft3gc972AA" name="anunt" content="anunt" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAnuntAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mzKmbrYyEeueft3gc972AA" name="anunt" dataType="_Q-PTVLQREeuju6Stncc5YQ" className="com.luxmob.model.DMAnuntAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mzKmb7YyEeueft3gc972AA" name="anuntInput.agent" content="anuntInput?.agent" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mzKmcLYyEeueft3gc972AA" name="anuntInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mzKmcbYyEeueft3gc972AA" type="JAVA_METHOD" expression="setAgent">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_mzKmcrYyEeueft3gc972AA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mzKmc7YyEeueft3gc972AA" name="anunt" content="anunt" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAnuntAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mzKmdLYyEeueft3gc972AA" name="anunt" dataType="_Q-PTVLQREeuju6Stncc5YQ" className="com.luxmob.model.DMAnuntAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mzKmdbYyEeueft3gc972AA" name="anuntInput.dataAnunt" content="anuntInput?.dataAnunt" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.OffsetDateTime">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mzKmdrYyEeueft3gc972AA" name="anuntInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mzKmd7YyEeueft3gc972AA" type="JAVA_METHOD" expression="setDataAnunt">
              <inputTypes>java.time.OffsetDateTime</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_mzKmeLYyEeueft3gc972AA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mzKmebYyEeueft3gc972AA" name="anunt" content="anunt" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAnuntAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mzKmerYyEeueft3gc972AA" name="anunt" dataType="_Q-PTVLQREeuju6Stncc5YQ" className="com.luxmob.model.DMAnuntAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mzKme7YyEeueft3gc972AA" name="anuntInput.oras" content="anuntInput?.oras" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mzKmfLYyEeueft3gc972AA" name="anuntInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mzKmfbYyEeueft3gc972AA" type="JAVA_METHOD" expression="setOras">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_mzKmfrYyEeueft3gc972AA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mzKmf7YyEeueft3gc972AA" name="anunt" content="anunt" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAnuntAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mzKmgLYyEeueft3gc972AA" name="anunt" dataType="_Q-PTVLQREeuju6Stncc5YQ" className="com.luxmob.model.DMAnuntAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mzKmgbYyEeueft3gc972AA" name="anuntInput.adresa" content="anuntInput?.adresa" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mzKmgrYyEeueft3gc972AA" name="anuntInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mzKmg7YyEeueft3gc972AA" type="JAVA_METHOD" expression="setAdresa">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_mzKmhLYyEeueft3gc972AA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mzKmhbYyEeueft3gc972AA" name="anunt" content="anunt" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAnuntAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mzKmhrYyEeueft3gc972AA" name="anunt" dataType="_Q-PTVLQREeuju6Stncc5YQ" className="com.luxmob.model.DMAnuntAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mzKmh7YyEeueft3gc972AA" name="anuntInput.zona" content="anuntInput?.zona" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mzKmiLYyEeueft3gc972AA" name="anuntInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mzKmibYyEeueft3gc972AA" type="JAVA_METHOD" expression="setZona">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_mzKmirYyEeueft3gc972AA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mzKmi7YyEeueft3gc972AA" name="anunt" content="anunt" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAnuntAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mzKmjLYyEeueft3gc972AA" name="anunt" dataType="_Q-PTVLQREeuju6Stncc5YQ" className="com.luxmob.model.DMAnuntAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mzKmjbYyEeueft3gc972AA" name="anuntInput.pret" content="anuntInput?.pret" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mzKmjrYyEeueft3gc972AA" name="anuntInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mzKmj7YyEeueft3gc972AA" type="JAVA_METHOD" expression="setPret">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_mzKmkLYyEeueft3gc972AA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mzKmkbYyEeueft3gc972AA" name="anunt" content="anunt" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAnuntAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mzKmkrYyEeueft3gc972AA" name="anunt" dataType="_Q-PTVLQREeuju6Stncc5YQ" className="com.luxmob.model.DMAnuntAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mzKmk7YyEeueft3gc972AA" name="anuntInput.compartimentare" content="anuntInput?.compartimentare" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mzKmlLYyEeueft3gc972AA" name="anuntInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mzKmlbYyEeueft3gc972AA" type="JAVA_METHOD" expression="setCompartimentare">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_mzKmlrYyEeueft3gc972AA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mzKml7YyEeueft3gc972AA" name="anunt" content="anunt" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAnuntAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mzKmmLYyEeueft3gc972AA" name="anunt" dataType="_Q-PTVLQREeuju6Stncc5YQ" className="com.luxmob.model.DMAnuntAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mzKmmbYyEeueft3gc972AA" name="anuntInput.etaj" content="anuntInput?.etaj" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mzKmmrYyEeueft3gc972AA" name="anuntInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mzKmm7YyEeueft3gc972AA" type="JAVA_METHOD" expression="setEtaj">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_mzKmnLYyEeueft3gc972AA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mzKmnbYyEeueft3gc972AA" name="anunt" content="anunt" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAnuntAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mzKmnrYyEeueft3gc972AA" name="anunt" dataType="_Q-PTVLQREeuju6Stncc5YQ" className="com.luxmob.model.DMAnuntAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mzKmn7YyEeueft3gc972AA" name="anuntInput.nrCamere" content="anuntInput?.nrCamere" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mzKmoLYyEeueft3gc972AA" name="anuntInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mzKmobYyEeueft3gc972AA" type="JAVA_METHOD" expression="setNrCamere">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_mzKmorYyEeueft3gc972AA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mzKmo7YyEeueft3gc972AA" name="anunt" content="anunt" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAnuntAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mzKmpLYyEeueft3gc972AA" name="anunt" dataType="_Q-PTVLQREeuju6Stncc5YQ" className="com.luxmob.model.DMAnuntAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mzKmpbYyEeueft3gc972AA" name="anuntInput.metriPatrati" content="anuntInput?.metriPatrati" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Double">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mzKmprYyEeueft3gc972AA" name="anuntInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mzKmp7YyEeueft3gc972AA" type="JAVA_METHOD" expression="setMetriPatrati">
              <inputTypes>java.lang.Double</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_4fL00LY1Eeueft3gc972AA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_4fL00bY1Eeueft3gc972AA" name="dateAnuntCorecte" content="dateAnuntCorecte" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_5RGZ8LY1Eeueft3gc972AA" name="dateAnuntCorecte" dataType="_Q-PTTLQREeuju6Stncc5YQ"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_4fL00rY1Eeueft3gc972AA" name="newScript()" content="if(&#xD;&#xA;&#x9;anuntInput.titlu != '' &amp;&amp;&#xD;&#xA;&#x9;anuntInput.adresa != '' &amp;&amp;&#xD;&#xA;&#x9;anuntInput.agent != '' &amp;&amp;&#xD;&#xA;&#x9;anuntInput.dataAnunt != '' &amp;&amp;&#xD;&#xA;&#x9;anuntInput.compartimentare != '' &amp;&amp;&#xD;&#xA;&#x9;anuntInput.etaj >= 0 &amp;&amp;&#xD;&#xA;&#x9;anuntInput.nrCamere > 0 &amp;&amp;&#xD;&#xA;&#x9;anuntInput.metriPatrati > 30 &amp;&amp;&#xD;&#xA;&#x9;anuntInput.pret > 10000&#xD;&#xA;&#x9;)&#xD;&#xA;&#x9;{&#xD;&#xA;&#x9;return true&#xD;&#xA;&#x9;}&#xD;&#xA;&#x9;else{&#xD;&#xA;&#x9;return false&#xD;&#xA;&#x9;}" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_-JQv0LZCEeueft3gc972AA" name="anuntInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_4fL007Y1Eeueft3gc972AA" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Q-PTK7QREeuju6Stncc5YQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Q-PTLLQREeuju6Stncc5YQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Q-PTLbQREeuju6Stncc5YQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Q-PTLrQREeuju6Stncc5YQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Q-PTL7QREeuju6Stncc5YQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Q-PTMLQREeuju6Stncc5YQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_DdbSILQUEeuju6Stncc5YQ" name="adaugareAnuntAgent" content="15b4382f-4fbb-4c30-b4b3-d7f3b22627d5" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Q-PTMrQREeuju6Stncc5YQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_mzJYQLYyEeueft3gc972AA" name="anuntInput" type="COMPLEX" dataReference="anunt">
              <inputs xmi:type="process:ContractInput" xmi:id="_mzJYQbYyEeueft3gc972AA" name="descriereAnunt"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_mzJYQrYyEeueft3gc972AA" name="titluAnunt"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_mzJYQ7YyEeueft3gc972AA" name="agent"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_mzJYRLYyEeueft3gc972AA" name="dataAnunt" type="OFFSETDATETIME"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_mzJYRbYyEeueft3gc972AA" name="oras"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_mzJYRrYyEeueft3gc972AA" name="adresa"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_mzJYR7YyEeueft3gc972AA" name="zona"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_mzJYSLYyEeueft3gc972AA" name="pret"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_mzJYSbYyEeueft3gc972AA" name="compartimentare"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_mzJYSrYyEeueft3gc972AA" name="etaj"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_mzJYS7YyEeueft3gc972AA" name="nrCamere" type="INTEGER"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_mzJYTLYyEeueft3gc972AA" name="metriPatrati" type="DECIMAL"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_mzJ_ULYyEeueft3gc972AA" expression="anuntInput?.titluAnunt != null" errorMessage="titluAnunt is mandatory for DMAnuntAgent" name="mandatory_anuntInput_titluAnunt">
              <inputNames>anuntInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_mzJ_UbYyEeueft3gc972AA" expression="anuntInput?.agent != null" errorMessage="agent is mandatory for DMAnuntAgent" name="mandatory_anuntInput_agent">
              <inputNames>anuntInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_mzJ_UrYyEeueft3gc972AA" expression="anuntInput?.dataAnunt != null" errorMessage="dataAnunt is mandatory for DMAnuntAgent" name="mandatory_anuntInput_dataAnunt">
              <inputNames>anuntInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_mzJ_U7YyEeueft3gc972AA" expression="anuntInput?.oras != null" errorMessage="oras is mandatory for DMAnuntAgent" name="mandatory_anuntInput_oras">
              <inputNames>anuntInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_mzJ_VLYyEeueft3gc972AA" expression="anuntInput?.adresa != null" errorMessage="adresa is mandatory for DMAnuntAgent" name="mandatory_anuntInput_adresa">
              <inputNames>anuntInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_mzJ_VbYyEeueft3gc972AA" expression="anuntInput?.pret != null" errorMessage="pret is mandatory for DMAnuntAgent" name="mandatory_anuntInput_pret">
              <inputNames>anuntInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_mzJ_VrYyEeueft3gc972AA" expression="anuntInput?.compartimentare != null" errorMessage="compartimentare is mandatory for DMAnuntAgent" name="mandatory_anuntInput_compartimentare">
              <inputNames>anuntInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_mzJ_V7YyEeueft3gc972AA" expression="anuntInput?.etaj != null" errorMessage="etaj is mandatory for DMAnuntAgent" name="mandatory_anuntInput_etaj">
              <inputNames>anuntInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_mzJ_WLYyEeueft3gc972AA" expression="anuntInput?.nrCamere != null" errorMessage="nrCamere is mandatory for DMAnuntAgent" name="mandatory_anuntInput_nrCamere">
              <inputNames>anuntInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_mzJ_WbYyEeueft3gc972AA" expression="anuntInput?.metriPatrati != null" errorMessage="metriPatrati is mandatory for DMAnuntAgent" name="mandatory_anuntInput_metriPatrati">
              <inputNames>anuntInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Q-PTM7QREeuju6Stncc5YQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_jS4vMLQREeuju6Stncc5YQ" name="Anunt adaugat" incoming="_jS_c4LQREeuju6Stncc5YQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jS4vMrQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jS4vMbQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jS4vM7QREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_0uN9oLQREeuju6Stncc5YQ" name="Selectare decizie" outgoing="_3iYuYLQREeuju6Stncc5YQ" incoming="_s1My8LQREeuju6Stncc5YQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_s1H6crQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_s1H6cbQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_s1H6c7QREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_8Jr4ALYyEeueft3gc972AA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_8Jr4AbYyEeueft3gc972AA" name="anunt" content="anunt" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAnuntAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8yZd0LYyEeueft3gc972AA" name="anunt" dataType="_Q-PTVLQREeuju6Stncc5YQ" className="com.luxmob.model.DMAnuntAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_8Jr4ArYyEeueft3gc972AA" content=""/>
            <operator xmi:type="expression:Operator" xmi:id="_8Jr4A7YyEeueft3gc972AA" type="DELETION"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Gv6P0LYzEeueft3gc972AA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Gv6P0bYzEeueft3gc972AA" name="decizieReincercare" content="decizieReincercare" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_HRzb8LYzEeueft3gc972AA" name="decizieReincercare" dataType="_Q-PTTLQREeuju6Stncc5YQ"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Gv6P0rYzEeueft3gc972AA" name="decizieReincercareInput" content="decizieReincercareInput" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_H3imQLYzEeueft3gc972AA" name="decizieReincercareInput" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_H3imQbYzEeueft3gc972AA"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Gv6P07YzEeueft3gc972AA" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_s1H6dLQREeuju6Stncc5YQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_s1H6dbQREeuju6Stncc5YQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_s1H6drQREeuju6Stncc5YQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_s1IhgbQREeuju6Stncc5YQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_s1IhgLQREeuju6Stncc5YQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_0uRA87QREeuju6Stncc5YQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_uX28ULYxEeueft3gc972AA" name="decizieReincercareCheckAnunt" content="969df731-3556-4d2a-8eca-b53fbc00a250" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_0uRA8rQREeuju6Stncc5YQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_yTAt0LYyEeueft3gc972AA" name="decizieReincercareInput" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_yTAt0bYyEeueft3gc972AA"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_0uRA9bQREeuju6Stncc5YQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_EzLPALQSEeuju6Stncc5YQ" name="Anunt anulat" incoming="_EzTK0LQSEeuju6Stncc5YQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EzL2EbQSEeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EzL2ELQSEeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EzL2ErQSEeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_K93PoLQSEeuju6Stncc5YQ" name="Validare date" outgoing="_jS_c4LQREeuju6Stncc5YQ _s1My8LQREeuju6Stncc5YQ" incoming="_h6jqULQREeuju6Stncc5YQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_h6fY4bQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_h6fY4LQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_h6fY4rQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_NyhvoLQSEeuju6Stncc5YQ" name="Reintroducere date" outgoing="_8lHBYLQREeuju6Stncc5YQ _EzTK0LQSEeuju6Stncc5YQ" incoming="_3iYuYLQREeuju6Stncc5YQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3iVEArQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3iVEAbQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3iVrELQREeuju6Stncc5YQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_tHEwkLTWEeu60qHvyVQuUA" name="dateAnuntCorecte" dataType="_Q-PTTLQREeuju6Stncc5YQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_tHEwkbTWEeu60qHvyVQuUA" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_U9OVALYxEeueft3gc972AA" name="decizieReincercare" dataType="_Q-PTTLQREeuju6Stncc5YQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_U9OVAbYxEeueft3gc972AA" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_WpwS0LYyEeueft3gc972AA" name="anunt" dataType="_Q-PTVLQREeuju6Stncc5YQ" className="com.luxmob.model.DMAnuntAgent">
        <defaultValue xmi:type="expression:Expression" xmi:id="_WpwS0bYyEeueft3gc972AA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_Q-PTNLQREeuju6Stncc5YQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_Li3LALY_Eeueft3gc972AA" name="adaugareAnuntAgentStart" content="17abe4ee-201a-41be-99d6-1ede160693d4" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_Q-PTNrQREeuju6Stncc5YQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_ehG9sLY_Eeueft3gc972AA" name="adaugareAnuntAgentOverview" content="0be3ec5a-539d-4f0f-a392-d664b4e6e216" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Q-PTOLQREeuju6Stncc5YQ" target="_Q-PTJ7QREeuju6Stncc5YQ" source="_Q-PTI7QREeuju6Stncc5YQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Q-PTObQREeuju6Stncc5YQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Q-PTOrQREeuju6Stncc5YQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_h6jqULQREeuju6Stncc5YQ" name="Date trimise" target="_K93PoLQSEeuju6Stncc5YQ" source="_Q-PTJ7QREeuju6Stncc5YQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_h6jqUbQREeuju6Stncc5YQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_h6jqUrQREeuju6Stncc5YQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jS_c4LQREeuju6Stncc5YQ" name="Date valide" target="_jS4vMLQREeuju6Stncc5YQ" source="_K93PoLQSEeuju6Stncc5YQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jTAD8LQREeuju6Stncc5YQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jTAD8bQREeuju6Stncc5YQ" name="newScript()" content="dateAnuntCorecte == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_DaW2ALZDEeueft3gc972AA" name="dateAnuntCorecte" dataType="_Q-PTTLQREeuju6Stncc5YQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s1My8LQREeuju6Stncc5YQ" name="Date invalide" target="_0uN9oLQREeuju6Stncc5YQ" source="_K93PoLQSEeuju6Stncc5YQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s1My8bQREeuju6Stncc5YQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_s1My8rQREeuju6Stncc5YQ" name="dateAnuntCorecte" content="dateAnuntCorecte == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_DPr8QLYxEeueft3gc972AA" name="dateAnuntCorecte" dataType="_Q-PTTLQREeuju6Stncc5YQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3iYuYLQREeuju6Stncc5YQ" target="_NyhvoLQSEeuju6Stncc5YQ" source="_0uN9oLQREeuju6Stncc5YQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3iYuYbQREeuju6Stncc5YQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_3iYuYrQREeuju6Stncc5YQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8lHBYLQREeuju6Stncc5YQ" name="Reintroducere date anunt" target="_Q-PTJ7QREeuju6Stncc5YQ" source="_NyhvoLQSEeuju6Stncc5YQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8lHocLQREeuju6Stncc5YQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_8lHocbQREeuju6Stncc5YQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EzTK0LQSEeuju6Stncc5YQ" name="Renuntare creare anunt" target="_EzLPALQSEeuju6Stncc5YQ" source="_NyhvoLQSEeuju6Stncc5YQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EzTK0bQSEeuju6Stncc5YQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_EzTK0rQSEeuju6Stncc5YQ" name="newScript()" content="decizieReincercare == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_vVdI0LY4Eeueft3gc972AA" name="decizieReincercare" dataType="_Q-PTTLQREeuju6Stncc5YQ"/>
        </condition>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_1_qQoLYwEeueft3gc972AA" name="Agent" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_Q-PTPLQREeuju6Stncc5YQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Q-PTPbQREeuju6Stncc5YQ">
        <name xmi:type="expression:Expression" xmi:id="_Q-PTPrQREeuju6Stncc5YQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Q-PTP7QREeuju6Stncc5YQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Q-PTQLQREeuju6Stncc5YQ">
        <name xmi:type="expression:Expression" xmi:id="_Q-PTQbQREeuju6Stncc5YQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Q-PTQrQREeuju6Stncc5YQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Q-PTQ7QREeuju6Stncc5YQ">
        <name xmi:type="expression:Expression" xmi:id="_Q-PTRLQREeuju6Stncc5YQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Q-PTRbQREeuju6Stncc5YQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Q-PTRrQREeuju6Stncc5YQ">
        <name xmi:type="expression:Expression" xmi:id="_Q-PTR7QREeuju6Stncc5YQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Q-PTSLQREeuju6Stncc5YQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Q-PTSbQREeuju6Stncc5YQ">
        <name xmi:type="expression:Expression" xmi:id="_Q-PTSrQREeuju6Stncc5YQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Q-PTS7QREeuju6Stncc5YQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_Q-PTTLQREeuju6Stncc5YQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_Q-PTTbQREeuju6Stncc5YQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_Q-PTTrQREeuju6Stncc5YQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_Q-PTT7QREeuju6Stncc5YQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_Q-PTULQREeuju6Stncc5YQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_Q-PTUbQREeuju6Stncc5YQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_Q-PTUrQREeuju6Stncc5YQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_Q-PTU7QREeuju6Stncc5YQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_Q-PTVLQREeuju6Stncc5YQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_Q-PTVbQREeuju6Stncc5YQ" type="Process" element="_Q-PTILQREeuju6Stncc5YQ" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_Q-PTVrQREeuju6Stncc5YQ" type="2007" element="_Q-PTIbQREeuju6Stncc5YQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_Q-PTV7QREeuju6Stncc5YQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_Q-PTWLQREeuju6Stncc5YQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_Q-PTWbQREeuju6Stncc5YQ" type="3007" element="_Q-PTIrQREeuju6Stncc5YQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_Q-PTWrQREeuju6Stncc5YQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Q-PTW7QREeuju6Stncc5YQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Q-PTXLQREeuju6Stncc5YQ" type="3005" element="_Q-PTJ7QREeuju6Stncc5YQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Q-PTXbQREeuju6Stncc5YQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q-PTXrQREeuju6Stncc5YQ" x="206" y="48" width="138" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Q-PTX7QREeuju6Stncc5YQ" type="3002" element="_Q-PTI7QREeuju6Stncc5YQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Q-PTYLQREeuju6Stncc5YQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Q-PTYbQREeuju6Stncc5YQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q-PTYrQREeuju6Stncc5YQ" x="86" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jS59ULQREeuju6Stncc5YQ" type="3003" element="_jS4vMLQREeuju6Stncc5YQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jS59UrQREeuju6Stncc5YQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jS59U7QREeuju6Stncc5YQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jS59UbQREeuju6Stncc5YQ" x="681" y="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0uRA9rQREeuju6Stncc5YQ" type="3005" element="_0uN9oLQREeuju6Stncc5YQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0uRA-LQREeuju6Stncc5YQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0uRA97QREeuju6Stncc5YQ" x="422" y="210" width="144" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EzNEMLQSEeuju6Stncc5YQ" type="3003" element="_EzLPALQSEeuju6Stncc5YQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_EzNrQLQSEeuju6Stncc5YQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_EzNrQbQSEeuju6Stncc5YQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EzNEMbQSEeuju6Stncc5YQ" x="677" y="351"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_K94dwLQSEeuju6Stncc5YQ" type="3008" element="_K93PoLQSEeuju6Stncc5YQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_K94dwrQSEeuju6Stncc5YQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_K94dw7QSEeuju6Stncc5YQ" x="3" y="-66"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_K94dwbQSEeuju6Stncc5YQ" x="470" y="62" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NyiWs7QSEeuju6Stncc5YQ" type="3008" element="_NyhvoLQSEeuju6Stncc5YQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_NyiWtbQSEeuju6Stncc5YQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_NyiWtrQSEeuju6Stncc5YQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NyiWtLQSEeuju6Stncc5YQ" x="473" y="346" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Q-PTY7QREeuju6Stncc5YQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Q-PTZLQREeuju6Stncc5YQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Q-PTZbQREeuju6Stncc5YQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Q-PTZrQREeuju6Stncc5YQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q-PTZ7QREeuju6Stncc5YQ" x="53" y="10" width="1292" height="550"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_Q-PTaLQREeuju6Stncc5YQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Q-PTabQREeuju6Stncc5YQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_Q-PTarQREeuju6Stncc5YQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_Q-PTa7QREeuju6Stncc5YQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q-PTbLQREeuju6Stncc5YQ" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Q-PTbbQREeuju6Stncc5YQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_Q-PTbrQREeuju6Stncc5YQ" type="4001" element="_Q-PTOLQREeuju6Stncc5YQ" source="_Q-PTX7QREeuju6Stncc5YQ" target="_Q-PTXLQREeuju6Stncc5YQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Q-PTb7QREeuju6Stncc5YQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Q-PTcLQREeuju6Stncc5YQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Q-PTcbQREeuju6Stncc5YQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Q-PTcrQREeuju6Stncc5YQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_h6kRYLQREeuju6Stncc5YQ" type="4001" element="_h6jqULQREeuju6Stncc5YQ" source="_Q-PTXLQREeuju6Stncc5YQ" target="_K94dwLQSEeuju6Stncc5YQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_h6k4cLQREeuju6Stncc5YQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_h6k4cbQREeuju6Stncc5YQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_h6kRYbQREeuju6Stncc5YQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_h6kRYrQREeuju6Stncc5YQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jTArALQREeuju6Stncc5YQ" type="4001" element="_jS_c4LQREeuju6Stncc5YQ" source="_K94dwLQSEeuju6Stncc5YQ" target="_jS59ULQREeuju6Stncc5YQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jTBSELQREeuju6Stncc5YQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jTBSEbQREeuju6Stncc5YQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jTArAbQREeuju6Stncc5YQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jTArArQREeuju6Stncc5YQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_s1My87QREeuju6Stncc5YQ" type="4001" element="_s1My8LQREeuju6Stncc5YQ" source="_K94dwLQSEeuju6Stncc5YQ" target="_0uRA9rQREeuju6Stncc5YQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_s1NaALQREeuju6Stncc5YQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_s1NaAbQREeuju6Stncc5YQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_s1My9LQREeuju6Stncc5YQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s1My9bQREeuju6Stncc5YQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3iZVcLQREeuju6Stncc5YQ" type="4001" element="_3iYuYLQREeuju6Stncc5YQ" source="_0uRA9rQREeuju6Stncc5YQ" target="_NyiWs7QSEeuju6Stncc5YQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3iZVc7QREeuju6Stncc5YQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3iZVdLQREeuju6Stncc5YQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3iZVcbQREeuju6Stncc5YQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3iZVcrQREeuju6Stncc5YQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8lHocrQREeuju6Stncc5YQ" type="4001" element="_8lHBYLQREeuju6Stncc5YQ" source="_NyiWs7QSEeuju6Stncc5YQ" target="_Q-PTXLQREeuju6Stncc5YQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8lIPgLQREeuju6Stncc5YQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8lIPgbQREeuju6Stncc5YQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8lHoc7QREeuju6Stncc5YQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8lHodLQREeuju6Stncc5YQ" points="[-43, -10, 198, 285]$[-238, -10, 3, 285]$[-238, -260, 3, 35]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8lKEsLQREeuju6Stncc5YQ" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EzTx4LQSEeuju6Stncc5YQ" type="4001" element="_EzTK0LQSEeuju6Stncc5YQ" source="_NyiWs7QSEeuju6Stncc5YQ" target="_EzNEMLQSEeuju6Stncc5YQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EzUY8LQSEeuju6Stncc5YQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EzUY8bQSEeuju6Stncc5YQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EzTx4bQSEeuju6Stncc5YQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EzTx4rQSEeuju6Stncc5YQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
