<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_F0DSoLQREeue1eVSe-c3yg" name="creareContAgentDiagram" author="Andrei" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_F0DSobQREeue1eVSe-c3yg" name="Agent">
      <elements xmi:type="process:Lane" xmi:id="_F0DSorQREeue1eVSe-c3yg" name="Agent" actor="_u16IELYiEeulO7C93GGECQ">
        <elements xmi:type="process:StartEvent" xmi:id="_F0DSo7QREeue1eVSe-c3yg" name="Accesare platformă" outgoing="_F0DSuLQREeue1eVSe-c3yg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F0DSpLQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F0DSpbQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F0DSprQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_F0DSp7QREeue1eVSe-c3yg" name="Introducere date creare" outgoing="_nFpPILQREeue1eVSe-c3yg" incoming="_F0DSuLQREeue1eVSe-c3yg _-37_oLQREeue1eVSe-c3yg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F0DSqLQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F0DSqbQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F0DSqrQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_w5pMXLYgEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_w5pMXbYgEeulO7C93GGECQ" name="agent" content="agent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_w5pMXrYgEeulO7C93GGECQ" name="agent" dataType="_F0DS1LQREeue1eVSe-c3yg" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_w5pMX7YgEeulO7C93GGECQ" name="agentInput.nume" content="agentInput?.nume" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_w5pMYLYgEeulO7C93GGECQ" name="agentInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_w5pMYbYgEeulO7C93GGECQ" type="JAVA_METHOD" expression="setNume">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_3lLQMLYgEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3lLQMbYgEeulO7C93GGECQ" name="dateValide" content="dateValide" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_4GwTQLYgEeulO7C93GGECQ" name="dateValide" dataType="_F0DSzLQREeue1eVSe-c3yg"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3lLQMrYgEeulO7C93GGECQ" name="newScript()" content="if(&#xD;&#xA;&#x9;agentInput.mail != '' &amp;&amp;&#xD;&#xA;&#x9;agentInput.parola != '' &amp;&amp;&#xD;&#xA;&#x9;agentInput.telefon != ''&#xD;&#xA;&#x9;)&#xD;&#xA;&#x9;{&#xD;&#xA;&#x9;// verificare daca sunt mai multi agenti cu aceeasi adresa de mail&#xD;&#xA;&#x9;if(dMAgentDAO.countForFindByMail(agentInput.mail) != 0){&#xD;&#xA;&#x9;// daca mai exista - date invalide&#xD;&#xA;&#x9;return false&#xD;&#xA;&#x9;}else{&#xD;&#xA;&#x9;// daca nu mai exista - utilizator nou - date valide&#xD;&#xA;&#x9;return true&#xD;&#xA;&#x9;}&#xD;&#xA;&#x9;}&#xD;&#xA;&#x9;else{&#xD;&#xA;&#x9;return false&#xD;&#xA;&#x9;}" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_s_-rwLYjEeulO7C93GGECQ" name="agentInput" type="COMPLEX"/>
              <referencedElements xmi:type="expression:Expression" xmi:id="_s_-rwbYjEeulO7C93GGECQ" name="dMAgentDAO" content="dMAgentDAO" type="TYPE_BUSINESS_OBJECT_DAO" returnType="com.luxmob.model.DMAgentDAO" returnTypeFixed="true"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3lLQM7YgEeulO7C93GGECQ" type="ASSIGNMENT"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_w5pMYrYgEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_w5pMY7YgEeulO7C93GGECQ" name="agent" content="agent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_w5pMZLYgEeulO7C93GGECQ" name="agent" dataType="_F0DS1LQREeue1eVSe-c3yg" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_w5pMZbYgEeulO7C93GGECQ" name="agentInput.prenume" content="agentInput?.prenume" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_w5pMZrYgEeulO7C93GGECQ" name="agentInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_w5pMZ7YgEeulO7C93GGECQ" type="JAVA_METHOD" expression="setPrenume">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_w5pMaLYgEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_w5pMabYgEeulO7C93GGECQ" name="agent" content="agent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_w5pMarYgEeulO7C93GGECQ" name="agent" dataType="_F0DS1LQREeue1eVSe-c3yg" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_w5pMa7YgEeulO7C93GGECQ" name="agentInput.adresa" content="agentInput?.adresa" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_w5pMbLYgEeulO7C93GGECQ" name="agentInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_w5pMbbYgEeulO7C93GGECQ" type="JAVA_METHOD" expression="setAdresa">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_w5pMbrYgEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_w5pMb7YgEeulO7C93GGECQ" name="agent" content="agent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_w5pMcLYgEeulO7C93GGECQ" name="agent" dataType="_F0DS1LQREeue1eVSe-c3yg" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_w5pMcbYgEeulO7C93GGECQ" name="agentInput.telefon" content="agentInput?.telefon" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_w5pMcrYgEeulO7C93GGECQ" name="agentInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_w5pMc7YgEeulO7C93GGECQ" type="JAVA_METHOD" expression="setTelefon">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_w5pMdLYgEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_w5pMdbYgEeulO7C93GGECQ" name="agent" content="agent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_w5pMdrYgEeulO7C93GGECQ" name="agent" dataType="_F0DS1LQREeue1eVSe-c3yg" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_w5pMd7YgEeulO7C93GGECQ" name="agentInput.agentie" content="agentInput?.agentie" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_w5pMeLYgEeulO7C93GGECQ" name="agentInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_w5pMebYgEeulO7C93GGECQ" type="JAVA_METHOD" expression="setAgentie">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_w5pMerYgEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_w5pMe7YgEeulO7C93GGECQ" name="agent" content="agent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_w5pMfLYgEeulO7C93GGECQ" name="agent" dataType="_F0DS1LQREeue1eVSe-c3yg" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_w5pMfbYgEeulO7C93GGECQ" name="agentInput.mail" content="agentInput?.mail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_w5pMfrYgEeulO7C93GGECQ" name="agentInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_w5pMf7YgEeulO7C93GGECQ" type="JAVA_METHOD" expression="setMail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_w5pMgLYgEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_w5pMgbYgEeulO7C93GGECQ" name="agent" content="agent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_w5pMgrYgEeulO7C93GGECQ" name="agent" dataType="_F0DS1LQREeue1eVSe-c3yg" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_w5pMg7YgEeulO7C93GGECQ" name="agentInput.parola" content="agentInput?.parola" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_w5pMhLYgEeulO7C93GGECQ" name="agentInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_w5pMhbYgEeulO7C93GGECQ" type="JAVA_METHOD" expression="setParola">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_F0DSq7QREeue1eVSe-c3yg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_F0DSrLQREeue1eVSe-c3yg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_F0DSrbQREeue1eVSe-c3yg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_F0DSrrQREeue1eVSe-c3yg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_F0DSr7QREeue1eVSe-c3yg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_F0DSsLQREeue1eVSe-c3yg">
            <targetForm xmi:type="expression:Expression" xmi:id="_45eVwLQUEeue1eVSe-c3yg" name="creareContAgent" content="322f101a-59e7-4aec-888c-3dad81b3e0df" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_F0DSsrQREeue1eVSe-c3yg">
            <inputs xmi:type="process:ContractInput" xmi:id="_w5pMULYgEeulO7C93GGECQ" name="agentInput" type="COMPLEX" dataReference="agent">
              <inputs xmi:type="process:ContractInput" xmi:id="_w5pMUbYgEeulO7C93GGECQ" name="nume"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_w5pMUrYgEeulO7C93GGECQ" name="prenume"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_w5pMU7YgEeulO7C93GGECQ" name="adresa"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_w5pMVLYgEeulO7C93GGECQ" name="telefon"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_w5pMVbYgEeulO7C93GGECQ" name="agentie"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_w5pMVrYgEeulO7C93GGECQ" name="mail"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_w5pMV7YgEeulO7C93GGECQ" name="parola"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_w5pMWLYgEeulO7C93GGECQ" expression="agentInput?.telefon != null" errorMessage="telefon is mandatory for DMAgent" name="mandatory_agentInput_telefon">
              <inputNames>agentInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_w5pMWbYgEeulO7C93GGECQ" expression="agentInput?.agentie != null" errorMessage="agentie is mandatory for DMAgent" name="mandatory_agentInput_agentie">
              <inputNames>agentInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_w5pMWrYgEeulO7C93GGECQ" expression="agentInput?.mail != null" errorMessage="mail is mandatory for DMAgent" name="mandatory_agentInput_mail">
              <inputNames>agentInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_w5pMW7YgEeulO7C93GGECQ" expression="agentInput?.parola != null" errorMessage="parola is mandatory for DMAgent" name="mandatory_agentInput_parola">
              <inputNames>agentInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_F0DSs7QREeue1eVSe-c3yg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_nZ2kkLQREeue1eVSe-c3yg" name="Validare date" outgoing="_xY8q8LQREeue1eVSe-c3yg _40yBcLYhEeulO7C93GGECQ" incoming="_nFpPILQREeue1eVSe-c3yg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nFe3ErQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nFe3EbQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nFe3E7QREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_orhAwLQREeue1eVSe-c3yg" name="Creare cont în sistem" incoming="_40yBcLYhEeulO7C93GGECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_orhAwrQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_orhAwbQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_orhAw7QREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_-X2KULQREeue1eVSe-c3yg" name="Decizie reîncercare" outgoing="_-37_oLQREeue1eVSe-c3yg __sBvALQREeue1eVSe-c3yg" incoming="_3fZEwLQREeue1eVSe-c3yg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3fVaYbQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3fVaYLQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3fVaYrQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="__r7oYLQREeue1eVSe-c3yg" name="Cont necreat" incoming="__sBvALQREeue1eVSe-c3yg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__r7oYrQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__r7oYbQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__r8PcLQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Cu1YsLQSEeue1eVSe-c3yg" name="Selectare decizie" outgoing="_3fZEwLQREeue1eVSe-c3yg" incoming="_xY8q8LQREeue1eVSe-c3yg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xYy58bQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xYy58LQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xYy58rQREeue1eVSe-c3yg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_O7LkULQTEeue1eVSe-c3yg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_O7LkUbQTEeue1eVSe-c3yg" name="decizieReîncercare" content="decizieReîncercare" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_PZOLMLQTEeue1eVSe-c3yg" name="decizieReîncercare" dataType="_F0DSzLQREeue1eVSe-c3yg"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_O7LkUrQTEeue1eVSe-c3yg" name="decizieReîncercareInput" content="decizieReîncercareInput" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_P5m7cLQTEeue1eVSe-c3yg" name="decizieReîncercareInput" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_P5m7cbQTEeue1eVSe-c3yg"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_O7LkU7QTEeue1eVSe-c3yg" type="ASSIGNMENT"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_9IIF8LYhEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_9IIF8bYhEeulO7C93GGECQ" name="agent" content="agent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_-Ck8ALYhEeulO7C93GGECQ" name="agent" dataType="_F0DS1LQREeue1eVSe-c3yg" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_9IIF8rYhEeulO7C93GGECQ" content=""/>
            <operator xmi:type="expression:Operator" xmi:id="_9IIF87YhEeulO7C93GGECQ" type="DELETION"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xYy587QREeue1eVSe-c3yg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xYy59LQREeue1eVSe-c3yg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xYy59bQREeue1eVSe-c3yg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xYy597QREeue1eVSe-c3yg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xYy59rQREeue1eVSe-c3yg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Cu1YurQSEeue1eVSe-c3yg">
            <targetForm xmi:type="expression:Expression" xmi:id="_FY45QLQUEeue1eVSe-c3yg" name="decizieReincercareCheckAgent" content="bc9261a1-91ce-4195-8dea-efe4b8c83b3b" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Cu1YubQSEeue1eVSe-c3yg">
            <inputs xmi:type="process:ContractInput" xmi:id="_LO0nULQTEeue1eVSe-c3yg" name="decizieReîncercareInput" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_LO0nUbQTEeue1eVSe-c3yg"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Cu1YvLQSEeue1eVSe-c3yg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_aPQWELQSEeue1eVSe-c3yg" name="decizieReîncercare" dataType="_F0DSzLQREeue1eVSe-c3yg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_aPQWEbQSEeue1eVSe-c3yg" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_m_8jULYgEeulO7C93GGECQ" name="dateValide" dataType="_F0DSzLQREeue1eVSe-c3yg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_m_8jUbYgEeulO7C93GGECQ" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_tzhI4LYgEeulO7C93GGECQ" name="agent" dataType="_F0DS1LQREeue1eVSe-c3yg" className="com.luxmob.model.DMAgent">
        <defaultValue xmi:type="expression:Expression" xmi:id="_tzhI4bYgEeulO7C93GGECQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_F0DStLQREeue1eVSe-c3yg">
        <targetForm xmi:type="expression:Expression" xmi:id="_aOoQILYkEeulO7C93GGECQ" name="creareContAgentStart" content="755291f2-e8c0-470c-8531-532658c64d8e" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_F0DStrQREeue1eVSe-c3yg">
        <targetForm xmi:type="expression:Expression" xmi:id="_uydgkLYkEeulO7C93GGECQ" name="creareContAgentOverview" content="ea23ecab-67d0-4928-bb4c-e0257c4e7fb3" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_F0DSuLQREeue1eVSe-c3yg" target="_F0DSp7QREeue1eVSe-c3yg" source="_F0DSo7QREeue1eVSe-c3yg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_F0DSubQREeue1eVSe-c3yg"/>
        <condition xmi:type="expression:Expression" xmi:id="_F0DSurQREeue1eVSe-c3yg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nFpPILQREeue1eVSe-c3yg" target="_nZ2kkLQREeue1eVSe-c3yg" source="_F0DSp7QREeue1eVSe-c3yg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nFpPIbQREeue1eVSe-c3yg"/>
        <condition xmi:type="expression:Expression" xmi:id="_nFpPIrQREeue1eVSe-c3yg" name="newScript()" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xY8q8LQREeue1eVSe-c3yg" name="Date invalide" target="_Cu1YsLQSEeue1eVSe-c3yg" source="_nZ2kkLQREeue1eVSe-c3yg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xY9SALQREeue1eVSe-c3yg"/>
        <condition xmi:type="expression:Expression" xmi:id="_xY9SAbQREeue1eVSe-c3yg" name="newScript()" content="dateValide == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_HM3r4LYjEeulO7C93GGECQ" name="dateValide" dataType="_F0DSzLQREeue1eVSe-c3yg"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3fZEwLQREeue1eVSe-c3yg" target="_-X2KULQREeue1eVSe-c3yg" source="_Cu1YsLQSEeue1eVSe-c3yg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3fZEwbQREeue1eVSe-c3yg"/>
        <condition xmi:type="expression:Expression" xmi:id="_3fZEwrQREeue1eVSe-c3yg" name="newScript()" content="decizieReîncercare == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_ht3TwLYiEeulO7C93GGECQ" name="decizieReîncercare" dataType="_F0DSzLQREeue1eVSe-c3yg"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-37_oLQREeue1eVSe-c3yg" name="Reîncercare creare" target="_F0DSp7QREeue1eVSe-c3yg" source="_-X2KULQREeue1eVSe-c3yg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-38msLQREeue1eVSe-c3yg"/>
        <condition xmi:type="expression:Expression" xmi:id="_-38msbQREeue1eVSe-c3yg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__sBvALQREeue1eVSe-c3yg" name="Renunțare creare cont" target="__r7oYLQREeue1eVSe-c3yg" source="_-X2KULQREeue1eVSe-c3yg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__sBvAbQREeue1eVSe-c3yg"/>
        <condition xmi:type="expression:Expression" xmi:id="__sBvArQREeue1eVSe-c3yg" name="newScript()" content="decizieReîncercare == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_WOjrULQTEeue1eVSe-c3yg" name="decizieReîncercare" dataType="_F0DSzLQREeue1eVSe-c3yg"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_40yBcLYhEeulO7C93GGECQ" name="Date valide" target="_orhAwLQREeue1eVSe-c3yg" source="_nZ2kkLQREeue1eVSe-c3yg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_40258LYhEeulO7C93GGECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_403hALYhEeulO7C93GGECQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_u16IELYiEeulO7C93GGECQ" name="Agent" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_F0DSvLQREeue1eVSe-c3yg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_F0DSvbQREeue1eVSe-c3yg">
        <name xmi:type="expression:Expression" xmi:id="_F0DSvrQREeue1eVSe-c3yg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_F0DSv7QREeue1eVSe-c3yg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_F0DSwLQREeue1eVSe-c3yg">
        <name xmi:type="expression:Expression" xmi:id="_F0DSwbQREeue1eVSe-c3yg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_F0DSwrQREeue1eVSe-c3yg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_F0DSw7QREeue1eVSe-c3yg">
        <name xmi:type="expression:Expression" xmi:id="_F0DSxLQREeue1eVSe-c3yg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_F0DSxbQREeue1eVSe-c3yg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_F0DSxrQREeue1eVSe-c3yg">
        <name xmi:type="expression:Expression" xmi:id="_F0DSx7QREeue1eVSe-c3yg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_F0DSyLQREeue1eVSe-c3yg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_F0DSybQREeue1eVSe-c3yg">
        <name xmi:type="expression:Expression" xmi:id="_F0DSyrQREeue1eVSe-c3yg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_F0DSy7QREeue1eVSe-c3yg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_F0DSzLQREeue1eVSe-c3yg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_F0DSzbQREeue1eVSe-c3yg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_F0DSzrQREeue1eVSe-c3yg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_F0DSz7QREeue1eVSe-c3yg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_F0DS0LQREeue1eVSe-c3yg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_F0DS0bQREeue1eVSe-c3yg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_F0DS0rQREeue1eVSe-c3yg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_F0DS07QREeue1eVSe-c3yg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_F0DS1LQREeue1eVSe-c3yg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_F0DS1bQREeue1eVSe-c3yg" type="Process" element="_F0DSoLQREeue1eVSe-c3yg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_F0DS1rQREeue1eVSe-c3yg" type="2007" element="_F0DSobQREeue1eVSe-c3yg">
      <children xmi:type="notation:DecorationNode" xmi:id="_F0DS17QREeue1eVSe-c3yg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_F0DS2LQREeue1eVSe-c3yg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_F0DS2bQREeue1eVSe-c3yg" type="3007" element="_F0DSorQREeue1eVSe-c3yg">
          <children xmi:type="notation:DecorationNode" xmi:id="_F0DS2rQREeue1eVSe-c3yg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_F0DS27QREeue1eVSe-c3yg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_F0DS3LQREeue1eVSe-c3yg" type="3005" element="_F0DSp7QREeue1eVSe-c3yg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_F0DS3bQREeue1eVSe-c3yg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F0DS3rQREeue1eVSe-c3yg" x="160" y="60" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_F0DS37QREeue1eVSe-c3yg" type="3002" element="_F0DSo7QREeue1eVSe-c3yg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_F0DS4LQREeue1eVSe-c3yg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_F0DS4bQREeue1eVSe-c3yg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F0DS4rQREeue1eVSe-c3yg" x="62" y="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nZ3LoLQREeue1eVSe-c3yg" type="3008" element="_nZ2kkLQREeue1eVSe-c3yg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_nZ3LorQREeue1eVSe-c3yg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_nZ3Lo7QREeue1eVSe-c3yg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nZ3LobQREeue1eVSe-c3yg" x="422" y="71" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_oriO4LQREeue1eVSe-c3yg" type="3003" element="_orhAwLQREeue1eVSe-c3yg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_oriO4rQREeue1eVSe-c3yg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_oriO47QREeue1eVSe-c3yg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oriO4bQREeue1eVSe-c3yg" x="662" y="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-X2xYLQREeue1eVSe-c3yg" type="3008" element="_-X2KULQREeue1eVSe-c3yg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_-X2xYrQREeue1eVSe-c3yg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_-X2xY7QREeue1eVSe-c3yg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-X2xYbQREeue1eVSe-c3yg" x="422" y="372" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__r8PcbQREeue1eVSe-c3yg" type="3003" element="__r7oYLQREeue1eVSe-c3yg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="__r82gLQREeue1eVSe-c3yg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="__r82gbQREeue1eVSe-c3yg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__r8PcrQREeue1eVSe-c3yg" x="634" y="379"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Cu1_wLQSEeue1eVSe-c3yg" type="3005" element="_Cu1YsLQSEeue1eVSe-c3yg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Cu1_wrQSEeue1eVSe-c3yg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Cu1_wbQSEeue1eVSe-c3yg" x="384" y="230" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_F0DS47QREeue1eVSe-c3yg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_F0DS5LQREeue1eVSe-c3yg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_F0DS5bQREeue1eVSe-c3yg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_F0DS5rQREeue1eVSe-c3yg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F0DS57QREeue1eVSe-c3yg" x="48" y="10" width="1297" height="550"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_F0DS6LQREeue1eVSe-c3yg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_F0DS6bQREeue1eVSe-c3yg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_F0DS6rQREeue1eVSe-c3yg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_F0DS67QREeue1eVSe-c3yg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F0DS7LQREeue1eVSe-c3yg" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_F0DS7bQREeue1eVSe-c3yg"/>
    <edges xmi:type="notation:Connector" xmi:id="_F0DS7rQREeue1eVSe-c3yg" type="4001" element="_F0DSuLQREeue1eVSe-c3yg" source="_F0DS37QREeue1eVSe-c3yg" target="_F0DS3LQREeue1eVSe-c3yg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_F0DS77QREeue1eVSe-c3yg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_F0DS8LQREeue1eVSe-c3yg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_F0DS8bQREeue1eVSe-c3yg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_F0DS8rQREeue1eVSe-c3yg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nFp2MLQREeue1eVSe-c3yg" type="4001" element="_nFpPILQREeue1eVSe-c3yg" source="_F0DS3LQREeue1eVSe-c3yg" target="_nZ3LoLQREeue1eVSe-c3yg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nFqdQLQREeue1eVSe-c3yg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nFqdQbQREeue1eVSe-c3yg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nFp2MbQREeue1eVSe-c3yg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nFp2MrQREeue1eVSe-c3yg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xZBjcLQREeue1eVSe-c3yg" type="4001" element="_xY8q8LQREeue1eVSe-c3yg" source="_nZ3LoLQREeue1eVSe-c3yg" target="_Cu1_wLQSEeue1eVSe-c3yg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xZBjc7QREeue1eVSe-c3yg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xZBjdLQREeue1eVSe-c3yg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xZBjcbQREeue1eVSe-c3yg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xZBjcrQREeue1eVSe-c3yg" points="[0, 22, -1, -146]$[0, 138, -1, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3fZr0LQREeue1eVSe-c3yg" type="4001" element="_3fZEwLQREeue1eVSe-c3yg" source="_Cu1_wLQSEeue1eVSe-c3yg" target="_-X2xYLQREeue1eVSe-c3yg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3fZr07QREeue1eVSe-c3yg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3fZr1LQREeue1eVSe-c3yg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3fZr0bQREeue1eVSe-c3yg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3fZr0rQREeue1eVSe-c3yg" points="[-1, 30, 0, -103]$[-1, 112, 0, -21]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-39NwLQREeue1eVSe-c3yg" type="4001" element="_-37_oLQREeue1eVSe-c3yg" source="_-X2xYLQREeue1eVSe-c3yg" target="_F0DS3LQREeue1eVSe-c3yg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-39Nw7QREeue1eVSe-c3yg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-39NxLQREeue1eVSe-c3yg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-39NwbQREeue1eVSe-c3yg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-39NwrQREeue1eVSe-c3yg" points="[-43, -6, 238, 282]$[-272, -6, 9, 282]$[-272, -278, 9, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-3-b4LQREeue1eVSe-c3yg" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-3-b4bQREeue1eVSe-c3yg" id="(0.35,0.8333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__sFZYLQREeue1eVSe-c3yg" type="4001" element="__sBvALQREeue1eVSe-c3yg" source="_-X2xYLQREeue1eVSe-c3yg" target="__r8PcbQREeue1eVSe-c3yg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__sFZY7QREeue1eVSe-c3yg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__sFZZLQREeue1eVSe-c3yg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__sFZYbQREeue1eVSe-c3yg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__sFZYrQREeue1eVSe-c3yg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_41AD4LYhEeulO7C93GGECQ" type="4001" element="_40yBcLYhEeulO7C93GGECQ" source="_nZ3LoLQREeue1eVSe-c3yg" target="_oriO4LQREeue1eVSe-c3yg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_41Aq8LYhEeulO7C93GGECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_41Aq8bYhEeulO7C93GGECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_41AD4bYhEeulO7C93GGECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_41AD4rYhEeulO7C93GGECQ" points="[-15, 0, -199, 13]$[182, 1, -2, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_41CgILYhEeulO7C93GGECQ" id="(1.0,0.813953488372093)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
