<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_f7g_ILTfEeu-0d2k7yYLTA" name="editareContAgentDiagram" author="unciu" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_f7g_IbTfEeu-0d2k7yYLTA" name="ContAgent">
      <elements xmi:type="process:Lane" xmi:id="_f7g_IrTfEeu-0d2k7yYLTA" name="Agent" actor="_vLX6YLYlEeulO7C93GGECQ">
        <elements xmi:type="process:StartEvent" xmi:id="_f7g_I7TfEeu-0d2k7yYLTA" name="Accesare platforma" outgoing="_qpPEkLYoEeulO7C93GGECQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_f7g_JLTfEeu-0d2k7yYLTA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_f7g_JbTfEeu-0d2k7yYLTA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_f7g_JrTfEeu-0d2k7yYLTA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_f7g_J7TfEeu-0d2k7yYLTA" name="Vizualizare date cont" outgoing="_0apVwLTfEeu-0d2k7yYLTA" incoming="__sJfMLTfEeu-0d2k7yYLTA _rKsy4LYoEeulO7C93GGECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_f7g_KLTfEeu-0d2k7yYLTA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_f7g_KbTfEeu-0d2k7yYLTA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_f7g_KrTfEeu-0d2k7yYLTA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_O3AlurYmEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_O3Alu7YmEeulO7C93GGECQ" name="contAgent" content="contAgent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_O3AlvLYmEeulO7C93GGECQ" name="contAgent" dataType="_f7g_VLTfEeu-0d2k7yYLTA" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_O3AlvbYmEeulO7C93GGECQ" name="contAgentInput.nume" content="contAgentInput?.nume" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_O3AlvrYmEeulO7C93GGECQ" name="contAgentInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_O3Alv7YmEeulO7C93GGECQ" type="JAVA_METHOD" expression="setNume">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_O3AlwLYmEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_O3AlwbYmEeulO7C93GGECQ" name="contAgent" content="contAgent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_O3AlwrYmEeulO7C93GGECQ" name="contAgent" dataType="_f7g_VLTfEeu-0d2k7yYLTA" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_O3Alw7YmEeulO7C93GGECQ" name="contAgentInput.prenume" content="contAgentInput?.prenume" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_O3AlxLYmEeulO7C93GGECQ" name="contAgentInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_O3AlxbYmEeulO7C93GGECQ" type="JAVA_METHOD" expression="setPrenume">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_O3AlxrYmEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_O3Alx7YmEeulO7C93GGECQ" name="contAgent" content="contAgent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_O3AlyLYmEeulO7C93GGECQ" name="contAgent" dataType="_f7g_VLTfEeu-0d2k7yYLTA" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_O3AlybYmEeulO7C93GGECQ" name="contAgentInput.adresa" content="contAgentInput?.adresa" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_O3AlyrYmEeulO7C93GGECQ" name="contAgentInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_O3Aly7YmEeulO7C93GGECQ" type="JAVA_METHOD" expression="setAdresa">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_O3AlzLYmEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_O3AlzbYmEeulO7C93GGECQ" name="contAgent" content="contAgent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_O3AlzrYmEeulO7C93GGECQ" name="contAgent" dataType="_f7g_VLTfEeu-0d2k7yYLTA" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_O3Alz7YmEeulO7C93GGECQ" name="contAgentInput.telefon" content="contAgentInput?.telefon" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_O3Al0LYmEeulO7C93GGECQ" name="contAgentInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_O3Al0bYmEeulO7C93GGECQ" type="JAVA_METHOD" expression="setTelefon">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_O3Al0rYmEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_O3Al07YmEeulO7C93GGECQ" name="contAgent" content="contAgent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_O3Al1LYmEeulO7C93GGECQ" name="contAgent" dataType="_f7g_VLTfEeu-0d2k7yYLTA" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_O3Al1bYmEeulO7C93GGECQ" name="contAgentInput.agentie" content="contAgentInput?.agentie" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_O3Al1rYmEeulO7C93GGECQ" name="contAgentInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_O3Al17YmEeulO7C93GGECQ" type="JAVA_METHOD" expression="setAgentie">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_O3Al2LYmEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_O3Al2bYmEeulO7C93GGECQ" name="contAgent" content="contAgent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_O3Al2rYmEeulO7C93GGECQ" name="contAgent" dataType="_f7g_VLTfEeu-0d2k7yYLTA" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_O3Al27YmEeulO7C93GGECQ" name="contAgentInput.parola" content="contAgentInput?.parola" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_O3Al3LYmEeulO7C93GGECQ" name="contAgentInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_O3Al3bYmEeulO7C93GGECQ" type="JAVA_METHOD" expression="setParola">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_WmrAELYmEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_WmrAEbYmEeulO7C93GGECQ" name="dateValide" content="dateValide" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_XKdCkLYmEeulO7C93GGECQ" name="dateValide" dataType="_f7g_TLTfEeu-0d2k7yYLTA"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_WmrAErYmEeulO7C93GGECQ" name="newScript()" content="if(&#xD;&#xA;&#x9;contAgentInput.parola == '' &amp;&amp;&#xD;&#xA;&#x9;contAgentInput.telefon == ''&#xD;&#xA;&#x9;)&#xD;&#xA;&#x9;{&#xD;&#xA;&#x9;&#x9;return false&#xD;&#xA;&#x9;}&#xD;&#xA;&#x9;else {&#xD;&#xA;&#x9;&#x9;return true&#xD;&#xA;&#x9;}" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_kUJcsLYmEeulO7C93GGECQ" name="contAgentInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_WmrAE7YmEeulO7C93GGECQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_f7g_K7TfEeu-0d2k7yYLTA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_f7g_LLTfEeu-0d2k7yYLTA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_f7g_LbTfEeu-0d2k7yYLTA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_f7g_LrTfEeu-0d2k7yYLTA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_f7g_L7TfEeu-0d2k7yYLTA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_f7g_MLTfEeu-0d2k7yYLTA">
            <targetForm xmi:type="expression:Expression" xmi:id="_6R7cwLTgEeu-0d2k7yYLTA" name="detaliiContAgent" content="791a1fc3-f794-4e9a-a29b-9496ea829dd5" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_f7g_MrTfEeu-0d2k7yYLTA">
            <inputs xmi:type="process:ContractInput" xmi:id="_O3AlsLYmEeulO7C93GGECQ" name="contAgentInput" type="COMPLEX" dataReference="contAgent" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_O3AlsbYmEeulO7C93GGECQ" name="nume" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_O3AlsrYmEeulO7C93GGECQ" name="prenume" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_O3Als7YmEeulO7C93GGECQ" name="adresa" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_O3AltLYmEeulO7C93GGECQ" name="telefon" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_O3AltbYmEeulO7C93GGECQ" name="agentie" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_O3AltrYmEeulO7C93GGECQ" name="parola" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_O3Alt7YmEeulO7C93GGECQ" expression="contAgentInput?.telefon != null" errorMessage="telefon is mandatory for DMAgent" name="mandatory_contAgentInput_telefon">
              <inputNames>contAgentInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_O3AluLYmEeulO7C93GGECQ" expression="contAgentInput?.agentie != null" errorMessage="agentie is mandatory for DMAgent" name="mandatory_contAgentInput_agentie">
              <inputNames>contAgentInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_O3AlubYmEeulO7C93GGECQ" expression="contAgentInput?.parola != null" errorMessage="parola is mandatory for DMAgent" name="mandatory_contAgentInput_parola">
              <inputNames>contAgentInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_f7g_M7TfEeu-0d2k7yYLTA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_6pUegLTfEeu-0d2k7yYLTA" name="Salvare date" outgoing="__sJfMLTfEeu-0d2k7yYLTA _CXJF0LTgEeu-0d2k7yYLTA" incoming="_0apVwLTfEeu-0d2k7yYLTA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0aYQArTfEeu-0d2k7yYLTA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0aYQAbTfEeu-0d2k7yYLTA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0aYQA7TfEeu-0d2k7yYLTA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_CW_74LTgEeu-0d2k7yYLTA" name="Actualizare date" incoming="_CXJF0LTgEeu-0d2k7yYLTA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_CW_74rTgEeu-0d2k7yYLTA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_CW_74bTgEeu-0d2k7yYLTA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_CW_747TgEeu-0d2k7yYLTA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_r1W5cLYoEeulO7C93GGECQ" name="Specificare mail" outgoing="_rKsy4LYoEeulO7C93GGECQ" incoming="_qpPEkLYoEeulO7C93GGECQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qo2qEbYoEeulO7C93GGECQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qo2qELYoEeulO7C93GGECQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qo2qErYoEeulO7C93GGECQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_0uVsVbYoEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_0uVsVrYoEeulO7C93GGECQ" name="contAgent" content="contAgent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0uVsV7YoEeulO7C93GGECQ" name="contAgent" dataType="_f7g_VLTfEeu-0d2k7yYLTA" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_0uVsWLYoEeulO7C93GGECQ" name="contAgentInput.mail" content="contAgentInput?.mail" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_0uVsWbYoEeulO7C93GGECQ" name="contAgentInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_0uVsWrYoEeulO7C93GGECQ" type="JAVA_METHOD" expression="setMail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_0uVsW7YoEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_0uVsXLYoEeulO7C93GGECQ" name="contAgent" content="contAgent" type="TYPE_VARIABLE" returnType="com.luxmob.model.DMAgent">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0uVsXbYoEeulO7C93GGECQ" name="contAgent" dataType="_f7g_VLTfEeu-0d2k7yYLTA" className="com.luxmob.model.DMAgent"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_0uVsXrYoEeulO7C93GGECQ" name="contAgentInput.parola" content="contAgentInput?.parola" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_0uVsX7YoEeulO7C93GGECQ" name="contAgentInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_0uVsYLYoEeulO7C93GGECQ" type="JAVA_METHOD" expression="setParola">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_KZtzoLYpEeulO7C93GGECQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_KZtzobYpEeulO7C93GGECQ" name="mailAgent" content="mailAgent" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_Kzb7MLYpEeulO7C93GGECQ" name="mailAgent" dataType="_f7g_UbTfEeu-0d2k7yYLTA"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_KZtzorYpEeulO7C93GGECQ" name="newScript()" content="return dMAgentDAO.findByMail(contAgentInput, 0, 1)[0]" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="expression:Expression" xmi:id="_L19gcLYvEeueft3gc972AA" name="dMAgentDAO" content="dMAgentDAO" type="TYPE_BUSINESS_OBJECT_DAO" returnType="com.luxmob.model.DMAgentDAO" returnTypeFixed="true"/>
              <referencedElements xmi:type="process:ContractInput" xmi:id="_L19gcbYvEeueft3gc972AA" name="contAgentInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_KZtzo7YpEeulO7C93GGECQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qo2qE7YoEeulO7C93GGECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qo2qFLYoEeulO7C93GGECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qo3RILYoEeulO7C93GGECQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qo3RIrYoEeulO7C93GGECQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qo3RIbYoEeulO7C93GGECQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_r1XgibYoEeulO7C93GGECQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_13fTcLYtEeueft3gc972AA" name="autentificareContAgentBUN" content="b23da435-6cc2-48eb-bc84-05c010c1394d" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_r1XgiLYoEeulO7C93GGECQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_0uVsULYoEeulO7C93GGECQ" name="contAgentInput" type="COMPLEX" dataReference="contAgent">
              <inputs xmi:type="process:ContractInput" xmi:id="_0uVsUbYoEeulO7C93GGECQ" name="mail"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_NgNRMLYuEeueft3gc972AA" name="parola">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_NgNRMbYuEeueft3gc972AA"/>
              </inputs>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_0uVsU7YoEeulO7C93GGECQ" expression="contAgentInput?.mail != null" errorMessage="mail is mandatory for DMAgent" name="mandatory_contAgentInput_mail">
              <inputNames>contAgentInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_0uVsVLYoEeulO7C93GGECQ" expression="contAgentInput?.parola != null" errorMessage="parola is mandatory for DMAgent" name="mandatory_contAgentInput_parola">
              <inputNames>contAgentInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_r1Xgi7YoEeulO7C93GGECQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_BzrSQLYmEeulO7C93GGECQ" name="dateValide" dataType="_f7g_TLTfEeu-0d2k7yYLTA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_BzrSQbYmEeulO7C93GGECQ" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_JaBYkLYmEeulO7C93GGECQ" name="contAgent" dataType="_f7g_VLTfEeu-0d2k7yYLTA" className="com.luxmob.model.DMAgent">
        <defaultValue xmi:type="expression:Expression" xmi:id="_JaBYkbYmEeulO7C93GGECQ" name="" content="" interpreter="GROOVY"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_Jj4X0LYpEeulO7C93GGECQ" name="mailAgent" dataType="_f7g_UbTfEeu-0d2k7yYLTA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Jj4X0bYpEeulO7C93GGECQ" name="" content="" interpreter="GROOVY"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_f7g_NLTfEeu-0d2k7yYLTA">
        <targetForm xmi:type="expression:Expression" xmi:id="_DHiXwLYvEeueft3gc972AA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_f7g_NrTfEeu-0d2k7yYLTA">
        <targetForm xmi:type="expression:Expression" xmi:id="_f7g_N7TfEeu-0d2k7yYLTA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0apVwLTfEeu-0d2k7yYLTA" target="_6pUegLTfEeu-0d2k7yYLTA" source="_f7g_J7TfEeu-0d2k7yYLTA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0apVwbTfEeu-0d2k7yYLTA"/>
        <condition xmi:type="expression:Expression" xmi:id="_0apVwrTfEeu-0d2k7yYLTA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__sJfMLTfEeu-0d2k7yYLTA" name="Anulare modificari" target="_f7g_J7TfEeu-0d2k7yYLTA" source="_6pUegLTfEeu-0d2k7yYLTA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__sJfMbTfEeu-0d2k7yYLTA"/>
        <condition xmi:type="expression:Expression" xmi:id="__sJfMrTfEeu-0d2k7yYLTA" name="newScript()" content="dateValide == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_TWMt0LYmEeulO7C93GGECQ" name="dateValide" dataType="_f7g_TLTfEeu-0d2k7yYLTA"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CXJF0LTgEeu-0d2k7yYLTA" name="Salvare modificari" target="_CW_74LTgEeu-0d2k7yYLTA" source="_6pUegLTfEeu-0d2k7yYLTA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CXJF0bTgEeu-0d2k7yYLTA"/>
        <condition xmi:type="expression:Expression" xmi:id="_CXJF0rTgEeu-0d2k7yYLTA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qpPEkLYoEeulO7C93GGECQ" target="_r1W5cLYoEeulO7C93GGECQ" source="_f7g_I7TfEeu-0d2k7yYLTA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qpPEkbYoEeulO7C93GGECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_qpPEkrYoEeulO7C93GGECQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rKsy4LYoEeulO7C93GGECQ" target="_f7g_J7TfEeu-0d2k7yYLTA" source="_r1W5cLYoEeulO7C93GGECQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rKtZ8LYoEeulO7C93GGECQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_rKtZ8bYoEeulO7C93GGECQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_vLX6YLYlEeulO7C93GGECQ" name="Agent" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_f7g_PLTfEeu-0d2k7yYLTA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f7g_PbTfEeu-0d2k7yYLTA">
        <name xmi:type="expression:Expression" xmi:id="_f7g_PrTfEeu-0d2k7yYLTA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f7g_P7TfEeu-0d2k7yYLTA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f7g_QLTfEeu-0d2k7yYLTA">
        <name xmi:type="expression:Expression" xmi:id="_f7g_QbTfEeu-0d2k7yYLTA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f7g_QrTfEeu-0d2k7yYLTA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f7g_Q7TfEeu-0d2k7yYLTA">
        <name xmi:type="expression:Expression" xmi:id="_f7g_RLTfEeu-0d2k7yYLTA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f7g_RbTfEeu-0d2k7yYLTA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f7g_RrTfEeu-0d2k7yYLTA">
        <name xmi:type="expression:Expression" xmi:id="_f7g_R7TfEeu-0d2k7yYLTA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f7g_SLTfEeu-0d2k7yYLTA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f7g_SbTfEeu-0d2k7yYLTA">
        <name xmi:type="expression:Expression" xmi:id="_f7g_SrTfEeu-0d2k7yYLTA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f7g_S7TfEeu-0d2k7yYLTA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_f7g_TLTfEeu-0d2k7yYLTA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_f7g_TbTfEeu-0d2k7yYLTA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_f7g_TrTfEeu-0d2k7yYLTA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_f7g_T7TfEeu-0d2k7yYLTA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_f7g_ULTfEeu-0d2k7yYLTA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_f7g_UbTfEeu-0d2k7yYLTA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_f7g_UrTfEeu-0d2k7yYLTA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_f7g_U7TfEeu-0d2k7yYLTA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_f7g_VLTfEeu-0d2k7yYLTA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_f7g_VbTfEeu-0d2k7yYLTA" type="Process" element="_f7g_ILTfEeu-0d2k7yYLTA" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_f7g_VrTfEeu-0d2k7yYLTA" type="2007" element="_f7g_IbTfEeu-0d2k7yYLTA">
      <children xmi:type="notation:DecorationNode" xmi:id="_f7g_V7TfEeu-0d2k7yYLTA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_f7g_WLTfEeu-0d2k7yYLTA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_f7g_WbTfEeu-0d2k7yYLTA" type="3007" element="_f7g_IrTfEeu-0d2k7yYLTA">
          <children xmi:type="notation:DecorationNode" xmi:id="_f7g_WrTfEeu-0d2k7yYLTA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_f7g_W7TfEeu-0d2k7yYLTA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_f7g_XLTfEeu-0d2k7yYLTA" type="3005" element="_f7g_J7TfEeu-0d2k7yYLTA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_f7g_XbTfEeu-0d2k7yYLTA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f7g_XrTfEeu-0d2k7yYLTA" x="350" y="46" width="146" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_f7g_X7TfEeu-0d2k7yYLTA" type="3002" element="_f7g_I7TfEeu-0d2k7yYLTA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_f7g_YLTfEeu-0d2k7yYLTA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_f7g_YbTfEeu-0d2k7yYLTA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f7g_YrTfEeu-0d2k7yYLTA" x="89" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6pVFk7TfEeu-0d2k7yYLTA" type="3008" element="_6pUegLTfEeu-0d2k7yYLTA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_6pVsoLTfEeu-0d2k7yYLTA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_6pVsobTfEeu-0d2k7yYLTA" x="-12" y="-73"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6pVFlLTfEeu-0d2k7yYLTA" x="622" y="58" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_CXBKALTgEeu-0d2k7yYLTA" type="3003" element="_CW_74LTgEeu-0d2k7yYLTA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_CXBKArTgEeu-0d2k7yYLTA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_CXBKA7TgEeu-0d2k7yYLTA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CXBKAbTgEeu-0d2k7yYLTA" x="847" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_r1XgjLYoEeulO7C93GGECQ" type="3005" element="_r1W5cLYoEeulO7C93GGECQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_r1XgjrYoEeulO7C93GGECQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r1XgjbYoEeulO7C93GGECQ" x="182" y="53" width="121" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_f7g_Y7TfEeu-0d2k7yYLTA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_f7g_ZLTfEeu-0d2k7yYLTA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_f7g_ZbTfEeu-0d2k7yYLTA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_f7g_ZrTfEeu-0d2k7yYLTA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f7g_Z7TfEeu-0d2k7yYLTA" x="53" y="10" width="1172" height="400"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_f7g_aLTfEeu-0d2k7yYLTA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_f7g_abTfEeu-0d2k7yYLTA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_f7g_arTfEeu-0d2k7yYLTA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_f7g_a7TfEeu-0d2k7yYLTA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f7g_bLTfEeu-0d2k7yYLTA" width="1200" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_f7g_bbTfEeu-0d2k7yYLTA"/>
    <edges xmi:type="notation:Connector" xmi:id="_0aqj4LTfEeu-0d2k7yYLTA" type="4001" element="_0apVwLTfEeu-0d2k7yYLTA" source="_f7g_XLTfEeu-0d2k7yYLTA" target="_6pVFk7TfEeu-0d2k7yYLTA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0aqj47TfEeu-0d2k7yYLTA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0arK8LTfEeu-0d2k7yYLTA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0aqj4bTfEeu-0d2k7yYLTA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0aqj4rTfEeu-0d2k7yYLTA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__sMigLTfEeu-0d2k7yYLTA" type="4001" element="__sJfMLTfEeu-0d2k7yYLTA" source="_6pVFk7TfEeu-0d2k7yYLTA" target="_f7g_XLTfEeu-0d2k7yYLTA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__sNJkLTfEeu-0d2k7yYLTA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__sNJkbTfEeu-0d2k7yYLTA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__sMigbTfEeu-0d2k7yYLTA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__sMigrTfEeu-0d2k7yYLTA" points="[-22, 12, 197, -5]$[-22, 169, 197, 152]$[-242, 169, -23, 152]$[-242, 30, -23, 13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__sQz8LTfEeu-0d2k7yYLTA" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__sRbALTfEeu-0d2k7yYLTA" id="(0.6575342465753424,0.821917808219178)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CXN-ULTgEeu-0d2k7yYLTA" type="4001" element="_CXJF0LTgEeu-0d2k7yYLTA" source="_6pVFk7TfEeu-0d2k7yYLTA" target="_CXBKALTgEeu-0d2k7yYLTA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CXOlYLTgEeu-0d2k7yYLTA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CXOlYbTgEeu-0d2k7yYLTA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CXN-UbTgEeu-0d2k7yYLTA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CXN-UrTgEeu-0d2k7yYLTA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qpProLYoEeulO7C93GGECQ" type="4001" element="_qpPEkLYoEeulO7C93GGECQ" source="_f7g_X7TfEeu-0d2k7yYLTA" target="_r1XgjLYoEeulO7C93GGECQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qpQSsLYoEeulO7C93GGECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qpQSsbYoEeulO7C93GGECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qpProbYoEeulO7C93GGECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qpProrYoEeulO7C93GGECQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rKtZ8rYoEeulO7C93GGECQ" type="4001" element="_rKsy4LYoEeulO7C93GGECQ" source="_r1XgjLYoEeulO7C93GGECQ" target="_f7g_XLTfEeu-0d2k7yYLTA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rKuBALYoEeulO7C93GGECQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rKuBAbYoEeulO7C93GGECQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rKtZ87YoEeulO7C93GGECQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rKtZ9LYoEeulO7C93GGECQ" points="[0, -4, -124, 7]$[51, -4, -73, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rKv2MLYoEeulO7C93GGECQ" id="(1.0,0.62)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
